### ISSUE TITLE
Error when suicide move 

### ISSUE THREAD

**Issue by YumJelly** [eagleflo/goban#2]
Hi:
Love your work:)
But when suicide move has been made 
the program will crash and the error as below:

self.board.groups.remove(self)
ValueError: list.remove(x): x not in list

can you fix it :)?

**Comment by YumJelly** [comment]
I try to change the function remove from line 115 in  go.py to as below :
 def remove(self):
        """Remove the entire group."""
        while self.stones:
            self.stones[0].remove()
        try:
            self.board.groups.remove(self)
        except ValueError:
            print("ValueError")
        del self

seems like the program didn't crash 
but I think it's not a right  way. xD

**Comment by eagleflo** [comment]
Hey! Thanks for taking interest in this very old project of mine and reporting the bug.

I think I've fixed it now.
