### ISSUE TITLE
sys.exit() method bug in goban.py

### ISSUE THREAD

**Issue by masihmozakka** [eagleflo/goban#3]
Hello,
I noticed an issue with the `exit()` method used in goban.py, `main` function for exiting the program. The program raised a SystemException error when quitting the game that from what I've found seems to be because the `sys.exit()` method requires an integer argument to specify exit status.
when `exit(0)` was used instead of `exit()` the program behaved normally.

**Comment by eagleflo** [comment]
See https://docs.python.org/3/library/sys.html#sys.exit:

> The optional argument arg can be an integer giving the exit status (defaulting to zero)

Raising a `SystemException` is how Python's `sys.exit` works internally; this way it can be caught by some outer layer in the program if need be. In this case we call it from the `main` function and let it pass all the way to the top, resulting in a successful termination of the program.
